export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION'
export const GET_CURRENT_LOCATION_START = 'GET_CURRENT_LOCATION_START'
export const GET_CURRENT_LOCATION_FAIL = 'GET_CURRENT_LOCATION_FAILT'

export const GET_WEATHER = 'GET_WEATHER'
export const SEARCH = 'SEARCH'

export const LOADING = " LOADING"
export const LOADING_END = "LOADING_END"
export const SEARCH_ERROR = 'SEARCH_ERROR'

export const ADD_TO_SAVE = 'ADD_TO_SAVE'

export const CLEARSEARCH = 'CLEARSEARCH'